### ISSUE TITLE
download station lädt nur html datei herunter

### ISSUE THREAD

**Issue by emil-sys** [iNaD/download-station-orfmediathek#3]
hosts hinzugefügt und link zur orf tvthek hinzugefügt. es wird leider nur die html datei heruntergeladen.

link: https://tvthek.orf.at/profile/Weltjournal/5298609/WELTjournal-Liebe-eine-Reise-um-die-Welt/14090446

**Comment by iNaD** [comment]
Wird gefixt bei der Integration in DS Mediatheken (https://github.com/iNaD/ds-mediatheken/issues/1)

Leider komme ich aus privaten Gründen aktuell kaum zum Entwickeln, weshalb sich das leider noch etwas hin ziehen wird.

**Comment by emil-sys** [comment]
Alles klar Daniel, danke jedenfalls für die Mühe!

LG Emil

Daniel Gehn ***@***.***> schrieb am Do., 20. Mai 2021, 15:19:
